name: Continuous Integration (Photo Prestige)

# De pipeline triggert bij elke push of Pull Request naar de main/master branch
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test-target-service:
    name: Test Target Service
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen uit GitHub
      uses: actions/checkout@v4

    - name: Node.js opzetten
      uses: actions/setup-node@v4
      with:
        node-node-version: 18

    - name: Dependencies installeren
      run: |
        cd photo-prestige/services/target-service
        npm install

    - name: Run Target Service Unittests
      run: |
        cd photo-prestige/services/target-service
        npm test


  test-score-service:
    name: Test Score Service
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen uit GitHub
      uses: actions/actions/checkout@v4

    - name: Node.js opzetten
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Dependencies installeren
      run: |
        cd photo-prestige/services/score-service
        npm install

    - name: Run Score Service Unittests
      run: |
        cd photo-prestige/services/score-service
        npm test